FROM ubuntu:24.04

# Install dependencies
RUN apt update -y && \
    apt install -y wget git zsh gpg && \
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg && \
    sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list' && \
    install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg && \
    rm -f packages.microsoft.gpg && \
    apt update -y && \
    apt install -y zip vim unzip jq telnet curl htop btop docker.io docker-compose python3 python3-pip eza micro btop apt-transport-https gpg zlib1g dotnet-sdk-8.0 dotnet-runtime-8.0 aspnetcore-runtime-8.0 sqlite3 fzf sudo && \
    apt autoclean -y && \
    apt autoremove -y && \
    # Install the latest version of Go 
    wget "https://go.dev/dl/$(curl https://go.dev/VERSION\?m=text | head -n 1).linux-$(dpkg --print-architecture).tar.gz" -O golang.tar.gz && \
    tar -C /usr/local -xzf golang.tar.gz && \
    rm golang.tar.gz && \    
    # code-server
    wget -qO- https://code-server.dev/install.sh | sh  

# Create a non-root user and prepare terminal and vim
RUN useradd -ms /bin/zsh -g root -G sudo -u 1001 coder
USER coder
WORKDIR /home/coder

# install env
RUN git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime && \
    sh ~/.vim_runtime/install_awesome_vimrc.sh && \
    echo set nu >> ~/.vim_runtime/my_configs.vim && \
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" && \
    echo 'alias ls="eza -hHbmgalT -L 1 --time-style=long-iso --icons"' >> ~/.bashrc && \
    echo 'alias lt="eza -hHbmgalT -L 4 --time-style=long-iso --icons"' >> ~/.bashrc && \
    echo 'PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc && \
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
    sed -i 's/ZSH_THEME=\"robbyrussell\"/ZSH_THEME=\"frisk\"/g' ~/.zshrc && \
    echo 'alias ls="eza -hHbmgalT -L 1 --time-style=long-iso --icons"' >> ~/.zshrc && \
    echo 'alias lt="eza -hHbmgalT -L 4 --time-style=long-iso --icons"' >> ~/.zshrc && \
    echo 'PATH=$PATH:/usr/local/go/bin' >> ~/.zshrc

# jvm
RUN curl -s https://get.sdkman.io | bash && \
    zsh -c 'source ~/.zshrc; sdk install java'

RUN mkdir .config && \
    mkdir .config/code-server && \
    echo 'bind-addr: 0.0.0.0:8080' >>  ~/.config/code-server/config.yaml && \
    echo 'auth: password' >>  ~/.config/code-server/config.yaml && \
    echo 'password: p@ssw0rd' >>  ~/.config/code-server/config.yaml

EXPOSE 8080

ENTRYPOINT [ "code-server" ]
